// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0vxKsVeN65c7DmAeAOFEsMxbaFFlNSWk',
    appId: '1:461278358090:web:719fcf441c981651cd14b3',
    messagingSenderId: '461278358090',
    projectId: 'spotlessyou-60c22',
    authDomain: 'spotlessyou-60c22.firebaseapp.com',
    storageBucket: 'spotlessyou-60c22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDGAkoipPYQh-gR7bW7CI3Pb7WJ25ywNg',
    appId: '1:461278358090:android:e570b7f82ae5d130cd14b3',
    messagingSenderId: '461278358090',
    projectId: 'spotlessyou-60c22',
    storageBucket: 'spotlessyou-60c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbeKfsYq5Zy-Bh-FHSa44x5KZYPN_Kja8',
    appId: '1:461278358090:ios:62fc7013a4379162cd14b3',
    messagingSenderId: '461278358090',
    projectId: 'spotlessyou-60c22',
    storageBucket: 'spotlessyou-60c22.appspot.com',
    iosBundleId: 'com.spotlessyou.spotlessyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbeKfsYq5Zy-Bh-FHSa44x5KZYPN_Kja8',
    appId: '1:461278358090:ios:62fc7013a4379162cd14b3',
    messagingSenderId: '461278358090',
    projectId: 'spotlessyou-60c22',
    storageBucket: 'spotlessyou-60c22.appspot.com',
    iosBundleId: 'com.spotlessyou.spotlessyou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0vxKsVeN65c7DmAeAOFEsMxbaFFlNSWk',
    appId: '1:461278358090:web:0767fdf6a4fc4babcd14b3',
    messagingSenderId: '461278358090',
    projectId: 'spotlessyou-60c22',
    authDomain: 'spotlessyou-60c22.firebaseapp.com',
    storageBucket: 'spotlessyou-60c22.appspot.com',
  );
}
